Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  # Download the aws "dummy" image if it isn't already isntalled
  config.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_KEY']
    aws.secret_access_key = ENV['AWS_SECRET']
    aws.keypair_name = ENV['AWS_KEYNAME'] 
    aws.region = "us-west-2"
    aws.subnet_id = "subnet-id"
    aws.ami = "ami-e7527ed7"
    aws.instance_type = "t2.micro"
    aws.security_groups = "sg-id"

    aws.tags = {
      'Name' => "name_of_instance"
    }
    aws.associate_public_ip = "true"
    override.ssh.username = "ec2-user"
    override.ssh.private_key_path = "~/path/to/pem"
  end
end
